
package vistas;

import Estructuras.Pila;
import javax.swing.JLabel;

public class FrmHome extends javax.swing.JFrame {

    /**
     * Creates new form FrmHome
     */
    public static int frameCount = 0;
    public static int frameCountProject = 0;
    public static Pila datosUsuario = new Pila();
    
    public FrmHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Principal = new javax.swing.JPanel();
        Lb_Titulo = new javax.swing.JLabel();
        Lb_Saludo = new javax.swing.JLabel();
        Panel_Izquierdo = new javax.swing.JPanel();
        BtnMiembros = new javax.swing.JButton();
        BtnProyectos = new javax.swing.JButton();
        Panel_Tareas_Asignadas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Desktop_Main = new javax.swing.JDesktopPane();
        TxtBuscarTareas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Principal.setBackground(new java.awt.Color(20, 29, 38));

        Lb_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lb_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Lb_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_24.png"))); // NOI18N
        Lb_Titulo.setText("HOME");

        Lb_Saludo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lb_Saludo.setForeground(new java.awt.Color(255, 255, 255));
        Lb_Saludo.setText("Bienvenido, ");

        Panel_Izquierdo.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Panel_IzquierdoLayout = new javax.swing.GroupLayout(Panel_Izquierdo);
        Panel_Izquierdo.setLayout(Panel_IzquierdoLayout);
        Panel_IzquierdoLayout.setHorizontalGroup(
            Panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        Panel_IzquierdoLayout.setVerticalGroup(
            Panel_IzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BtnMiembros.setBackground(new java.awt.Color(153, 216, 240));
        BtnMiembros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnMiembros.setForeground(new java.awt.Color(0, 172, 238));
        BtnMiembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/members_24.png"))); // NOI18N
        BtnMiembros.setText("Miembros");
        BtnMiembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMiembrosActionPerformed(evt);
            }
        });

        BtnProyectos.setBackground(new java.awt.Color(153, 216, 240));
        BtnProyectos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnProyectos.setForeground(new java.awt.Color(0, 172, 238));
        BtnProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Project.png"))); // NOI18N
        BtnProyectos.setText("Proyectos");
        BtnProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProyectosActionPerformed(evt);
            }
        });

        Panel_Tareas_Asignadas.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Tareas asginadas");

        javax.swing.GroupLayout Panel_Tareas_AsignadasLayout = new javax.swing.GroupLayout(Panel_Tareas_Asignadas);
        Panel_Tareas_Asignadas.setLayout(Panel_Tareas_AsignadasLayout);
        Panel_Tareas_AsignadasLayout.setHorizontalGroup(
            Panel_Tareas_AsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Tareas_AsignadasLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_Tareas_AsignadasLayout.setVerticalGroup(
            Panel_Tareas_AsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Tareas_AsignadasLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Desktop_Main.setBackground(new java.awt.Color(20, 29, 38));
        Desktop_Main.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, new java.awt.Color(153, 216, 240)));

        javax.swing.GroupLayout Desktop_MainLayout = new javax.swing.GroupLayout(Desktop_Main);
        Desktop_Main.setLayout(Desktop_MainLayout);
        Desktop_MainLayout.setHorizontalGroup(
            Desktop_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        Desktop_MainLayout.setVerticalGroup(
            Desktop_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        TxtBuscarTareas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtBuscarTareas.setForeground(new java.awt.Color(255, 255, 255));
        TxtBuscarTareas.setText("Buscar tareas");

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lb_Titulo)
                    .addComponent(Lb_Saludo)
                    .addComponent(BtnMiembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnProyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(Panel_Tareas_Asignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Desktop_Main)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TxtBuscarTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Izquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Izquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lb_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtBuscarTareas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addComponent(Lb_Saludo)
                                .addGap(67, 67, 67)
                                .addComponent(BtnMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Panel_Tareas_Asignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Desktop_Main))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMiembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMiembrosActionPerformed

        if(frameCount==0){
            FrmMiembros miembros = new FrmMiembros();
            miembros.setVisible(true);
            this.Desktop_Main.add(miembros);
            frameCount++;
        }
    }//GEN-LAST:event_BtnMiembrosActionPerformed

    private void BtnProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProyectosActionPerformed
        if(frameCountProject==0){
            FrmProyecto proyectos = new FrmProyecto();
            proyectos.setVisible(true);
            this.Desktop_Main.add(proyectos);
            frameCountProject++;
        }
    }//GEN-LAST:event_BtnProyectosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }

    public void setLb_Saludo_Text(String text) {
        this.Lb_Saludo.setText(this.Lb_Saludo.getText() + text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMiembros;
    private javax.swing.JButton BtnProyectos;
    public static javax.swing.JDesktopPane Desktop_Main;
    private javax.swing.JLabel Lb_Saludo;
    private javax.swing.JLabel Lb_Titulo;
    private javax.swing.JPanel Panel_Izquierdo;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_Tareas_Asignadas;
    private javax.swing.JTextField TxtBuscarTareas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
