/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import proyecto_final.Proyecto;

/**
 *
 * @author Freison
 */
public class FrmNuevoProyecto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmNuevoProyecto
     */
    public FrmNuevoProyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTitulo = new javax.swing.JLabel();
        LbTituloProyecto = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        LbDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDescripcion = new javax.swing.JTextArea();
        BtnCancelar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        CheckTablero = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(20, 29, 38));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        LbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LbTitulo.setText("Nuevo Proyecto");

        LbTituloProyecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbTituloProyecto.setForeground(new java.awt.Color(255, 255, 255));
        LbTituloProyecto.setText("Titulo");

        TxtTitulo.setBackground(new java.awt.Color(20, 29, 38));
        TxtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtTitulo.setForeground(new java.awt.Color(255, 255, 255));

        LbDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LbDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        LbDescripcion.setText("Descripción");

        TxtDescripcion.setBackground(new java.awt.Color(20, 29, 38));
        TxtDescripcion.setColumns(20);
        TxtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        TxtDescripcion.setRows(5);
        jScrollPane1.setViewportView(TxtDescripcion);

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(102, 102, 102));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(153, 216, 240));
        BtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(0, 172, 238));
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        CheckTablero.setBackground(new java.awt.Color(20, 29, 38));
        CheckTablero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CheckTablero.setForeground(new java.awt.Color(255, 255, 255));
        CheckTablero.setText("Tablero Personalizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(LbTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbTituloProyecto)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDescripcion)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckTablero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitulo)
                .addGap(18, 18, 18)
                .addComponent(LbTituloProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LbDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckTablero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        if(FrmHome.frameCountProject == 0){
            FrmProyecto proyecto = new FrmProyecto();
            proyecto.setVisible(true);
            FrmHome.Desktop_Main.add(proyecto);
            FrmHome.frameCountProject++;
        }
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        Proyecto proyecto = new Proyecto();
        proyecto.setNombre(this.TxtTitulo.getText().trim());
        proyecto.setDescripcion(this.TxtDescripcion.getText().trim());
        proyecto.Agregar(FrmHome.datosUsuario, false);
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JCheckBox CheckTablero;
    private javax.swing.JLabel LbDescripcion;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JLabel LbTituloProyecto;
    private javax.swing.JTextArea TxtDescripcion;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
